spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8082
  http2:
    enabled: true
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

